In [1]:
from sklearn.preprocessing import StandardScaler

In [2]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [3]:
scaler = StandardScaler()

In [4]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [5]:
scaler.mean_

array([ 0.5,  0.5])

In [6]:
scaler.var_

array([ 0.25,  0.25])

In [7]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [8]:
scaler.transform([[2, 2]])

array([[ 3.,  3.]])

In [9]:
import numpy as np

In [10]:
class MyStanderScaler:
    def __init__(self):
        self.data_mean_ = None
    
    def fit(self, data):
        self.data_mean_ = np.mean(data, axis=0)
        self.data_std_ = np.std(data, axis=0)
        
    def transform(self, data):
        new_data = (np.array(data)-self.data_mean_)/self.data_std_
        return new_data
    
    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)

In [11]:
myscaler = MyStanderScaler()

In [12]:
myscaler.fit(data)

In [13]:
myscaler.data_mean_

array([ 0.5,  0.5])

In [14]:
myscaler.data_std_

array([ 0.5,  0.5])

In [15]:
myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [16]:
myscaler_new = MyStanderScaler()

In [17]:
myscaler_new.fit_transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])